### ISSUE TITLE
(Composter) Fruit mash does not count for spoling, and thus does not spoil faster

### ISSUE THREAD

**Issue by 5HT2** [Craluminum-Mods/CraluminumMods-Issues#16]
**Game Version:** 1.16.4
**Mod Version:** v1.0.3

**Description:**
(Composter) Fruit mash does not count for spoling, and thus does not spoil faster.

![image](https://user-images.githubusercontent.com/17222512/160255638-c8de4b79-d369-415f-8a91-74968b194a0e.png)
![image](https://user-images.githubusercontent.com/17222512/160255640-bc4701fe-5708-4c57-a437-f9cf82fc240e.png)
![image](https://user-images.githubusercontent.com/17222512/160255644-4b3205a8-96df-4f16-a218-a84998bb05b5.png)

**Comment by Craluminum2413** [comment]
Fixed in 1.0.5
