### ISSUE TITLE
Compatibility with Farm Life?

### ISSUE THREAD

**Issue by genderneutralnoun** [Craluminum-Mods/CraluminumMods-Issues#19]
Title. I tried placing Animal Feed from Farm Life in the large troughs - which were already oak, in case that matters - and couldn't. I then changed the config to disable the variants of troughs, and still couldn't put the feed in the large oak troughs. For some reason, I can put the feed in small oak troughs, but I haven't tried to do so with the trough variants enabled. I think the HUD for the troughs also shows the vanilla info (as opposed to the Farm Life info), I think, because when I put rice in the large trough it said that pigs and sheep will eat it, but 1. my sheep did not eat it, and 2. it says on the page for Farm Life that pigs and sheep won't eat rice. If there's any other incompatibilities between these two mods, I'm unaware of them.

**Comment by Craluminum2413** [comment]
Have you tried without Vanilla Variants?

**Comment by genderneutralnoun** [comment]
Not yet, but I will soon, and report back.

**Comment by genderneutralnoun** [comment]
Tried that, it still didn't work. I guess it's a conflict with a different mod, sorry.

**Comment by Craluminum2413** [comment]
Do you have Medieval Expansion and/or Creatures and Critters installed?

**Comment by Craluminum2413** [comment]
Creatures and Critters completely overwrites "a list" which contains what animals can eat, I have no idea how to fix it
