### ISSUE TITLE
Branch Cutter - Dropped Leaves Don't Stack

### ISSUE THREAD

**Issue by kurazarrh** [Craluminum-Mods/CraluminumMods-Issues#35]
OS: Windows
Game Version: 1.18.1
Branch Cutter Version: 1.0.1

The issue I'm having is that each set of leaves that I shear does not stack in inventory, even if they are of the same type. I think it may have to do with how the game now tracks each spawned tree separately; shearing 2 different birch trees will provide 2 different sets of stacks each for the leaves and branchy leaves. same with each group of leaves on the ground. Placing and shearing these leaves again does not resolve the issue.

**Comment by Craluminum2413** [comment]
fixed
