### ISSUE TITLE
(Composter) Missing texture in mod

### ISSUE THREAD

**Issue by PhyDoesStuff** [Craluminum-Mods/CraluminumMods-Issues#36]
**Game Version:** 1.18.5
**Mod Version:** 1.0.4

**Description:**
A Warning in client-main.txt indicating a missing texture asset for composter:composter-north. Checking the mod's folder structure, assets/textures is missing.

**Log:**
```
4.6.2023 11:03:29 [Warning] Texture asset 'composter:textures/block/wood/debarked/oak.png' not found (defined in Baked inventory variant of block composter:composter-north).
```

**Comment by Craluminum2413** [comment]
This is in shape file, doesn't affect anything
