### ISSUE TITLE
(Multiblock Crates) Handbook Crash

### ISSUE THREAD

**Issue by VaelophisNyx** [Craluminum-Mods/CraluminumMods-Issues#43]
**Game Version:** 1.19.3
**Mod Version:** 1.2.0

**Description:**
Attempting to view any crate recipe from the stated mod crashes the game

**How to reproduce:**
1. open the handbook
2. search crate
3. attempt to click on any multiblock crate recipe
4. crash

**Expected behavior:**
functional recipes that don't crash would be expected 👍

**Screenshots / Videos:**
There's nothing visual that is really significant here

**Log:**
[client-main.txt](https://github.com/Craluminum-Mods/CraluminumMods-Issues/files/14234868/client-main.txt)
[client-crash.txt](https://github.com/Craluminum-Mods/CraluminumMods-Issues/files/14234869/client-crash.txt)

**Comment by VaelophisNyx** [comment]
other than that specific crash the mod works flawlessly in 1.19.3*

**Comment by Craluminum2413** [comment]
I can't find a bug that causes crash, probably will never get fixed because it worked perfectly before 1.19

**Comment by Craluminum2413** [comment]
I hid crafting recipes that caused crash, should be fixed for now
