### ISSUE TITLE
(Juicy Ores) Z-fighting when ore block is placed to the south side of tall display box

### ISSUE THREAD

**Issue by CROAC233** [Craluminum-Mods/CraluminumMods-Issues#45]
**Game Version:** 1.19.8
**Mod Version:** 1.0.0

**Description:**
When places to the south side of a block that is 1 voxel away, Z-fighting occurs.
The extra models should move 0.05 voxels inwards.

![2024-07-01_12-49-17](https://github.com/Craluminum-Mods/CraluminumMods-Issues/assets/106009479/dbc44b4a-0d0d-4022-a6e4-045dc165c4a4)
![2024-07-01_12-51-00](https://github.com/Craluminum-Mods/CraluminumMods-Issues/assets/106009479/18952e70-f847-469d-9b9e-edae40b8d86a)

**Comment by Craluminum2413** [comment]
I won't fix it
