### ISSUE TITLE
Tools Require Rope v1.2.1 - Issue still persists

### ISSUE THREAD

**Issue by daashr** [Craluminum-Mods/CraluminumMods-Issues#46]
**Game Version:** 1.19.8
**Mod Version:** 1.2.1

**Description:**
The issue still persists. 

I think that since - as you have already described - Adze & Mallet are not considered a “tool”, a compatibility is difficult. With the current approach, however, it doesn't seem to work quite right. 

You have patched the recipe for Pemmican, but now Adze, Mallet and co. no longer have a rope in the crafting grid. 

Aditionally, for Adze and Mallet you can't change the config from "null" to "rope" or something similiar. 

Easiest solution would be if I just create my own patch for the Adze and mallet, since the version v1.1.0 of Tools require Ropes was the one with the least amount of bugs.

I've attached my config file, so you can see how it looks. As well as ingame images. 
![image](https://github.com/user-attachments/assets/50f2056b-990a-4a0c-8279-38a4f2a83e93)

![image](https://github.com/user-attachments/assets/4395a5ea-0434-4bed-97ed-40fdf3add51e)

[ToolsRequireRope.json](https://github.com/user-attachments/files/16415285/ToolsRequireRope.json)

**Comment by Craluminum2413** [comment]
Also your config file has only null values for adze and mallet

**Comment by daashr** [comment]
Oh my god. I forgot the ',' at the end of he line in my last try. Thank you.
