### ISSUE TITLE
DanaTweaks Errors

### ISSUE THREAD

**Issue by ashyvaane** [Craluminum-Mods/CraluminumMods-Issues#47]
This mod is throwing a lot of errors on my server - I've attached a copy of both client and server logs for you. Additionally, "cooling with watering can" doesn't appear to be working.
[Client Logs.zip](https://github.com/user-attachments/files/16831514/Client.Logs.zip)
[Server Logs.gz](https://github.com/user-attachments/files/16831515/Server.Logs.gz)

**Comment by Craluminum2413** [comment]
Could you please upload all logs to pastebin?

**Comment by ashyvaane** [comment]
I would gladly, but I am unfamiliar with pastebin and am unsure where I should be looking for it. I hate to be a bother, but can you point me in the right direction?

**Comment by Craluminum2413** [comment]
@ashyvaane https://pastebin.com/

**Comment by Craluminum2413** [comment]
@ashyvaane Did the mod work before and it broke right after you updated it to 3.2.0?

**Comment by Craluminum2413** [comment]
@ashyvaane Also, does the mod work in superflat world when it is the only installed mod?

**Comment by ashyvaane** [comment]
So many options for pastebin wow o.o Can I post them publicly as a guest, any specific tags?

As far as I remember, it did work before I updated it. I'm about to try running it alone to see if it works there.

**Comment by ashyvaane** [comment]
Correction - we are running 3.1, not 3.2 - I'll move forward first and if it doesn't work, I'll roll back to 3.0

**Comment by ashyvaane** [comment]
It appears that moving forward to the most current version actually fixes the watercan cooling molds mechanic! Both on it's own and with my, frankly, insane server mod load. If anyone else complains of it not working like my goofy butt, that's the first fix I would suggest - I'm so sorry for wasting your time on it. 

It was another dev that pointed out the excessive errors issue, so I'm not certain what I'd be looking for now that I'm updating the server.

**Comment by ashyvaane** [comment]
I stand corrected - I have updated the server and the cooling mechanic does not work still.

**Comment by Craluminum2413** [comment]
@ashyvaane Does cooling mechanic work with only Dana Tweaks installed?

**Comment by ashyvaane** [comment]
Yes it does

**Comment by Craluminum2413** [comment]
@ashyvaane Maybe it is conflicting with xskills, if so, then there is nothing i can do to make it work

**Comment by ashyvaane** [comment]
Okay, thank you though!
