### ISSUE TITLE
(Extra Info) Texture memory leak

### ISSUE THREAD

**Issue by fiqusonnick** [Craluminum-Mods/CraluminumMods-Issues#50]
**Game Version:** 1.19.8
**Mod Version:** 1.8.1

**Description:**
After I started getting random crashes I looked at the console output and saw almost 100 lines like this:
`[Client Debug] Texture with texture id ### is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.`
I narrowed it down to Extra Info.

**How to reproduce:**
1. Run VS via .NET console (`<PATH_DO_DOTNET>/dotnet.exe Vintagestory.dll`)
2. Open any world (or even create one)
3. Game may crash when loading (I'm not sure if this is even related)
4. If it didn't and the world loads, the console will show what I described above.

**Expected behavior:**
No mentions any memory leaking

**Screenshots / Videos:**
N/A

**Log:**
Console output for both crash and no-crash cases, as well as nonempty logs for no-crash, included.
[server-main.txt](https://github.com/user-attachments/files/17166850/server-main.txt)
[server-audit.txt](https://github.com/user-attachments/files/17166851/server-audit.txt)
[client-chat.txt](https://github.com/user-attachments/files/17166852/client-chat.txt)
[client-audit.txt](https://github.com/user-attachments/files/17166853/client-audit.txt)
[client-main.txt](https://github.com/user-attachments/files/17166854/client-main.txt)
[client-debug.txt](https://github.com/user-attachments/files/17166855/client-debug.txt)
[server-event.txt](https://github.com/user-attachments/files/17166856/server-event.txt)
[server-storyevent.txt](https://github.com/user-attachments/files/17166857/server-storyevent.txt)
[server-debug.txt](https://github.com/user-attachments/files/17166858/server-debug.txt)
[console_crash.txt](https://github.com/user-attachments/files/17166860/console_crash.txt)
[console_nocrash.txt](https://github.com/user-attachments/files/17166861/console_nocrash.txt)

**Comment by Craluminum2413** [comment]
I don't use any textures

**Comment by fiqusonnick** [comment]
I noticed, but I don't get that message When I run the game with all my other mods and disable extra info.

I'll admit I know next to nothing about Harmony, is there a chance you're patching a function that does some resource freeing in a way that would skip it?

**Comment by Craluminum2413** [comment]
@fiqusonnick Nope

**Comment by fiqusonnick** [comment]
Welp, thanks thanks for the clarification, now I'm even more confused 🙃
