### ISSUE TITLE
DanaCanCook

### ISSUE THREAD

**Issue by ashyvaane** [Craluminum-Mods/CraluminumMods-Issues#51]
Sammiches are rotting ingredient by ingredient instead of as a whole, and this process causes client crashes. We discovered this on my server when people picked up sammiches off shelves, causing an instant crash. When they logged back in, the sammich in question is in their inventory with at least one ingredient of it turned to rot. While I was on troubleshooting, I had a batch of sammiches in my inventory - initially, I thought it was a Food Shelves mod update that broke. However, my client crashed without requiring interacting with shelves or storage vessels. Instead, when I logged back on, one or more sammiches had rotted components that were not previously rotted.

I've attached the latest logs from our server, my crashes and severe lag should appear at the very end of it (username unhallowed).

[latest.log](https://github.com/user-attachments/files/17198197/latest.log)

**Comment by ashyvaane** [comment]
We only have Dana Can Cook installed, not the sammiches mod - I'm just super lazy typing that word.

**Comment by Craluminum2413** [comment]
@ashyvaane Try new version

**Comment by ashyvaane** [comment]
Thank you!!
