### ISSUE TITLE
(Dana Can Cook) Sandwiches can't be eaten

### ISSUE THREAD

**Issue by ashyvaane** [Craluminum-Mods/CraluminumMods-Issues#52]
Hello! Happy to report that the rot-related crashing has stopped, but now sandwiches cannot be consumed.

**Comment by Craluminum2413** [comment]
Are you using 0.2.3 version?

**Comment by ashyvaane** [comment]
I did not see there was an update, my apologies! Updating to 0.2.3 fixed it.
