### ISSUE TITLE
DanaTweaks: cannot create items using tree log stack

### ISSUE THREAD

**Issue by roman4e** [Craluminum-Mods/CraluminumMods-Issues#53]
**Game Version:** 1.9.8
**Mod Version:** 3.2.2

**Description:**
Found by disabling modes one by one that with DanaTweaks lost an ability to create things using tree log stacks e.g. raft, at the most beginning of the game.

**How to reproduce:**
1. Prepare 3 ropes, an axe
2. Cut any common tree
3. You gather tree logs one by one, no stacking
4. Try to create a raft. Cannot stack tree logs.

**Expected behavior:**
Expected to have a tree logs stack at least 4 items per one stack. To put onto creation panel log stack as is.

**Screenshots / Videos:**
Raft recipe
![screenshot_2024-10-15_21-47-09](https://github.com/user-attachments/assets/6c58f96b-746b-4c47-9d91-31b22d90b9eb)

No stacking in hands/bag (you see logs on the ground can't be taken because no stacks):
![screenshot_2024-10-15_21-59-58](https://github.com/user-attachments/assets/a6a97079-8194-4fc2-9829-0138e9fd98ff)

No stacking while creation
![screenshot_2024-10-15_21-47-55](https://github.com/user-attachments/assets/46be5415-da36-4174-a6f3-6b714702449f)

**Comment by Craluminum2413** [comment]
@roman4e Are you sure it is Dana Tweaks and not Configure Everything?

**Comment by Craluminum2413** [comment]
@roman4e Can't reproduce

**Comment by Craluminum2413** [comment]
@roman4e So it looks like it is caused by TrullyWoods, my mod has nothing to do with it

**Comment by roman4e** [comment]
Thanks for extremely fast answer
