### ISSUE TITLE
VV 6.0.2 game 1.20.pre11 missing recipe?

### ISSUE THREAD

**Issue by DejFidOFF** [Craluminum-Mods/CraluminumMods-Issues#58]
**Game Version:**1.20pre11
**Mod Version:** 6.0.2
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-aged-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-aged-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-aged-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-birch-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-birch-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-birch-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-maple-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-maple-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-maple-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-pine-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-pine-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-pine-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-acacia-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-acacia-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-acacia-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-kapok-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-kapok-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-kapok-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-baldcypress-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-baldcypress-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-baldcypress-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-larch-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-larch-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-larch-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-ebony-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-ebony-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-ebony-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-walnut-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-walnut-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-walnut-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-purpleheart-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-purpleheart-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-purpleheart-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-aged-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-aged-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-aged-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-birch-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-birch-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-birch-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-maple-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-maple-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-maple-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-pine-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-pine-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-pine-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-acacia-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-acacia-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-acacia-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-kapok-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-kapok-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-kapok-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-baldcypress-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-baldcypress-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-baldcypress-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-larch-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-larch-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-larch-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-ebony-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-ebony-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-ebony-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-walnut-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-walnut-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-walnut-ne-ud
9.11.2024 08:49:46 [Warning] Failed resolving crafting recipe ingredient with code game:logsection-placed-purpleheart-ne-ud in Grid recipe
9.11.2024 08:49:46 [Error] Grid Recipe with output Block code vanvar:brake-purpleheart-north contains an ingredient that cannot be resolved: Block code game:logsection-placed-purpleheart-ne-ud

**Comment by Craluminum2413** [comment]
Ignore these
