### ISSUE TITLE
VanillaVariants-v6.0.3 No texture for filled trough

### ISSUE THREAD

**Issue by DejFidOFF** [Craluminum-Mods/CraluminumMods-Issues#59]
**Game Version:** VanillaVariants-v6.0.3
**Mod Version:** 1.20.pre11

![2024-11-10_19-57-18](https://github.com/user-attachments/assets/5a2ec99d-c255-489f-868e-280a255630ea)

**Comment by Craluminum2413** [comment]
Fixed in 6.0.4
