### ISSUE TITLE
(PEI) Mushrooms!

### ISSUE THREAD

**Issue by SmeeSlug** [Craluminum-Mods/CraluminumMods-Issues#7]
It would be great if all the mushrooms were placeable.

**Comment by Craluminum2413** [comment]
Yeah, I will try to add that, because last time when I tried, it crashed for me

**Comment by Craluminum2413** [comment]
So I started doing that. Mushrooms are block and placed only as block state (in Ground Storage), that is fair for any block

**Comment by Craluminum2413** [comment]
I will implement it once vanilla get a way to dynamically change shapes of placed items in Ground Storage

**Comment by Craluminum2413** [comment]
Will be added in 1.4.0
